### ISSUE TITLE
mask_input 

### ISSUE THREAD

**Issue by meshiguge** [bdhingra/tweet2vec#4]
hi,   the mask_input was used in GRU layer
`l_mask = lasagne.layers.InputLayer(shape=(N_BATCH,MAX_LENGTH), input_var=mask, name='mask')
`
according to this [tutorial](https://github.com/craffel/Lasagne-tutorial/blob/master/examples/tutorial.ipynb) 
should `N_BATCH` be replaced with `None`? as the n_batchs are not equal in all batch ?

**Comment by bdhingra** [comment]
Yes, that can be replaced with None as the last batch in an epoch may not be equal to `N_BATCH`. I have not seen any issues running the code as it is though.

**Comment by meshiguge** [comment]
dear bdhingra, how about the `MAX_LENGTH`, every input sequence is  also different, should I replace it also?

**Comment by bdhingra** [comment]
No, the second dimension of the input will always have size `MAX_LENGTH`. See [this](https://github.com/bdhingra/tweet2vec/blob/5abfe4bca6c10c51d1687b2c873cddca670b2970/tweet2vec/batch_char.py#L72).

**Comment by meshiguge** [comment]
may I ask why did't use different input sequence ?  as tweets have many short sequence?
